services:
  e2e:
    container_name: e2e
    image: cypress/included:latest
    working_dir: /app
    volumes:
      - ./e2e:/app
    depends_on:
      - proxy
    entrypoint: []

  proxy:
    container_name: proxy
    hostname: seki
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - NGINX_HOST=seki
      - NGINX_PORT=80
    depends_on:
      - web
      - api

  web:
    container_name: web
    image: node:alpine
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./web:/app
    command: ["sh", "./entrypoint.sh"]

  api:
    container_name: api
    image: elixir:alpine
    working_dir: /app
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
    command: ["sh", "./entrypoint.sh"]
