name: API

on:
  push:
    paths:
      - ".github/**"
      - "api/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1.17
        with:
          elixir-version: "1.17"
          otp-version: "27.0"
      - id: mix-cache
        uses: actions/cache/restore@v4
        with:
          path: |
            api/_build
            api/deps
          key: ${{ runner.os }}-${{ hashFiles('mix.lock') }}
      - if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix deps.get --check
          mix compile --all-warnings --warnings-as-errors

      - if: steps.mix-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            api/_build
            api/deps
          key: ${{ runner.os }}-${{ hashFiles('mix.lock') }}
      #- run: mix deps.get --check
      #- run: mix compile --all-warnings --warnings-as-errors
      #- uses: actions/upload-artifact@v4
      #  with:
      #    name: build
      #    if-no-files-found: error
      #    path: |
      #      api/_build
      #      api/deps
      #    include-hidden-files: true

  format:
    name: Check format
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1.17
        with:
          elixir-version: "1.17"
          otp-version: "27.0"
      - uses: actions/cache@v4
        with:
          path: |
            api/_build
            api/deps
          key: ${{ runner.os }}-${{ hashFiles('mix.lock') }}
      - run: mix format --check-formatted

  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    needs: build

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1.17
        with:
          elixir-version: "1.17"
          otp-version: "27.0"
      - uses: actions/cache@v4
        with:
          path: |
            api/_build
            api/deps
          key: ${{ runner.os }}-${{ hashFiles('mix.lock') }}
      - run: mix test --all-warnings --warnings-as-errors

  credo:
    name: Credo
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    needs: build

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1.17
        with:
          elixir-version: "1.17"
          otp-version: "27.0"
      - uses: actions/cache@v4
        with:
          path: |
            api/_build
            api/deps
          key: ${{ runner.os }}-${{ hashFiles('mix.lock') }}
      - run: mix credo -a --strict

  dialyzer:
    name: Dialyzer
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    needs: build

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1.17
        with:
          elixir-version: "1.17"
          otp-version: "27.0"
      - uses: actions/cache@v4
        with:
          path: |
            api/_build
            api/deps
          key: ${{ runner.os }}-${{ hashFiles('mix.lock') }}
      - run: mix dialyzer
