name: API

on:
  push:
    paths:
      - ".github/**"
      - "api/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1.17
        with:
          elixir-version: "1.17"
          otp-version: "27.0"
      - run: mix deps.get --check
      - run: mix compile --no-deps-check --warnings-as-errors
      - uses: actions/upload-artifact@v4
        with:
          name: build
          if-no-files-found: error
          path: _build

  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    needs: build

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: _build
      - run: mix test

  credo:
    name: Credo
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    needs: build

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: _build
      - run: mix credo -a --strict

  dialyzer:
    name: Dialyzer
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    needs: build

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: _build
      - run: mix dialyzer
