name: E2E

on: [push]

jobs:
  e2e:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./compose.yaml"
          services: proxy
      - run: docker-compose run e2e cypress run
